// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: price-service.proto

package priceServicePackage

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ItemDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId   int64  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName string `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ShopId   int64  `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
}

func (x *ItemDetail) Reset() {
	*x = ItemDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDetail) ProtoMessage() {}

func (x *ItemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDetail.ProtoReflect.Descriptor instead.
func (*ItemDetail) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{0}
}

func (x *ItemDetail) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemDetail) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ItemDetail) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type ItemPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int64 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Price  int32 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Time   int64 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *ItemPrice) Reset() {
	*x = ItemPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemPrice) ProtoMessage() {}

func (x *ItemPrice) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemPrice.ProtoReflect.Descriptor instead.
func (*ItemPrice) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{1}
}

func (x *ItemPrice) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemPrice) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemPrice) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type PriceLogItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price int32 `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Time  int64 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *PriceLogItem) Reset() {
	*x = PriceLogItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLogItem) ProtoMessage() {}

func (x *PriceLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLogItem.ProtoReflect.Descriptor instead.
func (*PriceLogItem) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{2}
}

func (x *PriceLogItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceLogItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ReadItemDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int64 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *ReadItemDetailRequest) Reset() {
	*x = ReadItemDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadItemDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadItemDetailRequest) ProtoMessage() {}

func (x *ReadItemDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadItemDetailRequest.ProtoReflect.Descriptor instead.
func (*ReadItemDetailRequest) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadItemDetailRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type ReadItemDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemDetail *ItemDetail `protobuf:"bytes,1,opt,name=itemDetail,proto3" json:"itemDetail,omitempty"`
	NotFound   int64       `protobuf:"varint,2,opt,name=notFound,proto3" json:"notFound,omitempty"`
}

func (x *ReadItemDetailResponse) Reset() {
	*x = ReadItemDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadItemDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadItemDetailResponse) ProtoMessage() {}

func (x *ReadItemDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadItemDetailResponse.ProtoReflect.Descriptor instead.
func (*ReadItemDetailResponse) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadItemDetailResponse) GetItemDetail() *ItemDetail {
	if x != nil {
		return x.ItemDetail
	}
	return nil
}

func (x *ReadItemDetailResponse) GetNotFound() int64 {
	if x != nil {
		return x.NotFound
	}
	return 0
}

type ReadItemInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId []int64 `protobuf:"varint,1,rep,packed,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *ReadItemInfoRequest) Reset() {
	*x = ReadItemInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadItemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadItemInfoRequest) ProtoMessage() {}

func (x *ReadItemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadItemInfoRequest.ProtoReflect.Descriptor instead.
func (*ReadItemInfoRequest) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadItemInfoRequest) GetItemId() []int64 {
	if x != nil {
		return x.ItemId
	}
	return nil
}

type ReadItemInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemDetails []*ItemDetail `protobuf:"bytes,1,rep,name=item_details,json=itemDetails,proto3" json:"item_details,omitempty"`
}

func (x *ReadItemInfoResponse) Reset() {
	*x = ReadItemInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadItemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadItemInfoResponse) ProtoMessage() {}

func (x *ReadItemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadItemInfoResponse.ProtoReflect.Descriptor instead.
func (*ReadItemInfoResponse) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadItemInfoResponse) GetItemDetails() []*ItemDetail {
	if x != nil {
		return x.ItemDetails
	}
	return nil
}

type CreateItemDetailPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int64 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ShopId int64 `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
}

func (x *CreateItemDetailPriceRequest) Reset() {
	*x = CreateItemDetailPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateItemDetailPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemDetailPriceRequest) ProtoMessage() {}

func (x *CreateItemDetailPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemDetailPriceRequest.ProtoReflect.Descriptor instead.
func (*CreateItemDetailPriceRequest) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateItemDetailPriceRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CreateItemDetailPriceRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type CreateItemDetailPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success int64 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreateItemDetailPriceResponse) Reset() {
	*x = CreateItemDetailPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateItemDetailPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemDetailPriceResponse) ProtoMessage() {}

func (x *CreateItemDetailPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemDetailPriceResponse.ProtoReflect.Descriptor instead.
func (*CreateItemDetailPriceResponse) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateItemDetailPriceResponse) GetSuccess() int64 {
	if x != nil {
		return x.Success
	}
	return 0
}

type ReadPriceChangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int64 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *ReadPriceChangeRequest) Reset() {
	*x = ReadPriceChangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPriceChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPriceChangeRequest) ProtoMessage() {}

func (x *ReadPriceChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPriceChangeRequest.ProtoReflect.Descriptor instead.
func (*ReadPriceChangeRequest) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReadPriceChangeRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type ReadPriceChangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*PriceLogItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	NotFound int64           `protobuf:"varint,2,opt,name=notFound,proto3" json:"notFound,omitempty"`
}

func (x *ReadPriceChangeResponse) Reset() {
	*x = ReadPriceChangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPriceChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPriceChangeResponse) ProtoMessage() {}

func (x *ReadPriceChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPriceChangeResponse.ProtoReflect.Descriptor instead.
func (*ReadPriceChangeResponse) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReadPriceChangeResponse) GetList() []*PriceLogItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ReadPriceChangeResponse) GetNotFound() int64 {
	if x != nil {
		return x.NotFound
	}
	return 0
}

var File_price_service_proto protoreflect.FileDescriptor

var file_price_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x70, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0x5b, 0x0a, 0x0a, 0x49, 0x74,
	0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x4c, 0x6f, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x22, 0x30, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74,
	0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a,
	0x0a, 0x69, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x6e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x2e, 0x0a, 0x13, 0x52, 0x65,
	0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x14, 0x52, 0x65,
	0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x42, 0x0a, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0b, 0x69, 0x74, 0x65, 0x6d, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x50, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x31, 0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x46,
	0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x46,
	0x6f, 0x75, 0x6e, 0x64, 0x32, 0xcd, 0x03, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6a, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x2a, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x7e, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x31, 0x2e, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x6c, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2c, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x63, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x28, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x3b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_price_service_proto_rawDescOnce sync.Once
	file_price_service_proto_rawDescData = file_price_service_proto_rawDesc
)

func file_price_service_proto_rawDescGZIP() []byte {
	file_price_service_proto_rawDescOnce.Do(func() {
		file_price_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_price_service_proto_rawDescData)
	})
	return file_price_service_proto_rawDescData
}

var file_price_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_price_service_proto_goTypes = []interface{}{
	(*ItemDetail)(nil),                    // 0: priceServicePackage.ItemDetail
	(*ItemPrice)(nil),                     // 1: priceServicePackage.ItemPrice
	(*PriceLogItem)(nil),                  // 2: priceServicePackage.PriceLogItem
	(*ReadItemDetailRequest)(nil),         // 3: priceServicePackage.ReadItemDetailRequest
	(*ReadItemDetailResponse)(nil),        // 4: priceServicePackage.ReadItemDetailResponse
	(*ReadItemInfoRequest)(nil),           // 5: priceServicePackage.ReadItemInfoRequest
	(*ReadItemInfoResponse)(nil),          // 6: priceServicePackage.ReadItemInfoResponse
	(*CreateItemDetailPriceRequest)(nil),  // 7: priceServicePackage.CreateItemDetailPriceRequest
	(*CreateItemDetailPriceResponse)(nil), // 8: priceServicePackage.CreateItemDetailPriceResponse
	(*ReadPriceChangeRequest)(nil),        // 9: priceServicePackage.ReadPriceChangeRequest
	(*ReadPriceChangeResponse)(nil),       // 10: priceServicePackage.ReadPriceChangeResponse
}
var file_price_service_proto_depIdxs = []int32{
	0,  // 0: priceServicePackage.ReadItemDetailResponse.itemDetail:type_name -> priceServicePackage.ItemDetail
	0,  // 1: priceServicePackage.ReadItemInfoResponse.item_details:type_name -> priceServicePackage.ItemDetail
	2,  // 2: priceServicePackage.ReadPriceChangeResponse.list:type_name -> priceServicePackage.PriceLogItem
	3,  // 3: priceServicePackage.PriceService.ReadItemDetails:input_type -> priceServicePackage.ReadItemDetailRequest
	7,  // 4: priceServicePackage.PriceService.CreateItemDetailPrice:input_type -> priceServicePackage.CreateItemDetailPriceRequest
	9,  // 5: priceServicePackage.PriceService.ReadPriceChange:input_type -> priceServicePackage.ReadPriceChangeRequest
	5,  // 6: priceServicePackage.PriceService.ReadItemInfo:input_type -> priceServicePackage.ReadItemInfoRequest
	4,  // 7: priceServicePackage.PriceService.ReadItemDetails:output_type -> priceServicePackage.ReadItemDetailResponse
	8,  // 8: priceServicePackage.PriceService.CreateItemDetailPrice:output_type -> priceServicePackage.CreateItemDetailPriceResponse
	10, // 9: priceServicePackage.PriceService.ReadPriceChange:output_type -> priceServicePackage.ReadPriceChangeResponse
	6,  // 10: priceServicePackage.PriceService.ReadItemInfo:output_type -> priceServicePackage.ReadItemInfoResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_price_service_proto_init() }
func file_price_service_proto_init() {
	if File_price_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_price_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceLogItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadItemDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadItemDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadItemInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadItemInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateItemDetailPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateItemDetailPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPriceChangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPriceChangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_price_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_price_service_proto_goTypes,
		DependencyIndexes: file_price_service_proto_depIdxs,
		MessageInfos:      file_price_service_proto_msgTypes,
	}.Build()
	File_price_service_proto = out.File
	file_price_service_proto_rawDesc = nil
	file_price_service_proto_goTypes = nil
	file_price_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PriceServiceClient is the client API for PriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PriceServiceClient interface {
	ReadItemDetails(ctx context.Context, in *ReadItemDetailRequest, opts ...grpc.CallOption) (*ReadItemDetailResponse, error)
	CreateItemDetailPrice(ctx context.Context, in *CreateItemDetailPriceRequest, opts ...grpc.CallOption) (*CreateItemDetailPriceResponse, error)
	// rpc ReadFlashSales(ReadFlashSalesRequest) returns (ReadFlashSalesResponse);
	ReadPriceChange(ctx context.Context, in *ReadPriceChangeRequest, opts ...grpc.CallOption) (*ReadPriceChangeResponse, error)
	ReadItemInfo(ctx context.Context, in *ReadItemInfoRequest, opts ...grpc.CallOption) (*ReadItemInfoResponse, error)
}

type priceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceServiceClient(cc grpc.ClientConnInterface) PriceServiceClient {
	return &priceServiceClient{cc}
}

func (c *priceServiceClient) ReadItemDetails(ctx context.Context, in *ReadItemDetailRequest, opts ...grpc.CallOption) (*ReadItemDetailResponse, error) {
	out := new(ReadItemDetailResponse)
	err := c.cc.Invoke(ctx, "/priceServicePackage.PriceService/ReadItemDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) CreateItemDetailPrice(ctx context.Context, in *CreateItemDetailPriceRequest, opts ...grpc.CallOption) (*CreateItemDetailPriceResponse, error) {
	out := new(CreateItemDetailPriceResponse)
	err := c.cc.Invoke(ctx, "/priceServicePackage.PriceService/CreateItemDetailPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) ReadPriceChange(ctx context.Context, in *ReadPriceChangeRequest, opts ...grpc.CallOption) (*ReadPriceChangeResponse, error) {
	out := new(ReadPriceChangeResponse)
	err := c.cc.Invoke(ctx, "/priceServicePackage.PriceService/ReadPriceChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) ReadItemInfo(ctx context.Context, in *ReadItemInfoRequest, opts ...grpc.CallOption) (*ReadItemInfoResponse, error) {
	out := new(ReadItemInfoResponse)
	err := c.cc.Invoke(ctx, "/priceServicePackage.PriceService/ReadItemInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceServiceServer is the server API for PriceService service.
type PriceServiceServer interface {
	ReadItemDetails(context.Context, *ReadItemDetailRequest) (*ReadItemDetailResponse, error)
	CreateItemDetailPrice(context.Context, *CreateItemDetailPriceRequest) (*CreateItemDetailPriceResponse, error)
	// rpc ReadFlashSales(ReadFlashSalesRequest) returns (ReadFlashSalesResponse);
	ReadPriceChange(context.Context, *ReadPriceChangeRequest) (*ReadPriceChangeResponse, error)
	ReadItemInfo(context.Context, *ReadItemInfoRequest) (*ReadItemInfoResponse, error)
}

// UnimplementedPriceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPriceServiceServer struct {
}

func (*UnimplementedPriceServiceServer) ReadItemDetails(context.Context, *ReadItemDetailRequest) (*ReadItemDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadItemDetails not implemented")
}
func (*UnimplementedPriceServiceServer) CreateItemDetailPrice(context.Context, *CreateItemDetailPriceRequest) (*CreateItemDetailPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItemDetailPrice not implemented")
}
func (*UnimplementedPriceServiceServer) ReadPriceChange(context.Context, *ReadPriceChangeRequest) (*ReadPriceChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPriceChange not implemented")
}
func (*UnimplementedPriceServiceServer) ReadItemInfo(context.Context, *ReadItemInfoRequest) (*ReadItemInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadItemInfo not implemented")
}

func RegisterPriceServiceServer(s *grpc.Server, srv PriceServiceServer) {
	s.RegisterService(&_PriceService_serviceDesc, srv)
}

func _PriceService_ReadItemDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadItemDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).ReadItemDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceServicePackage.PriceService/ReadItemDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).ReadItemDetails(ctx, req.(*ReadItemDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceService_CreateItemDetailPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemDetailPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).CreateItemDetailPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceServicePackage.PriceService/CreateItemDetailPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).CreateItemDetailPrice(ctx, req.(*CreateItemDetailPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceService_ReadPriceChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPriceChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).ReadPriceChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceServicePackage.PriceService/ReadPriceChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).ReadPriceChange(ctx, req.(*ReadPriceChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceService_ReadItemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadItemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).ReadItemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceServicePackage.PriceService/ReadItemInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).ReadItemInfo(ctx, req.(*ReadItemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PriceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "priceServicePackage.PriceService",
	HandlerType: (*PriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadItemDetails",
			Handler:    _PriceService_ReadItemDetails_Handler,
		},
		{
			MethodName: "CreateItemDetailPrice",
			Handler:    _PriceService_CreateItemDetailPrice_Handler,
		},
		{
			MethodName: "ReadPriceChange",
			Handler:    _PriceService_ReadPriceChange_Handler,
		},
		{
			MethodName: "ReadItemInfo",
			Handler:    _PriceService_ReadItemInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "price-service.proto",
}
